USE SCHEMA FLYWISE_AI_DB.GOLD;

-- Track notification lifecycle on each flight
ALTER TABLE GOLD.GOLD_FLIGHT_DATA
ADD COLUMN IF NOT EXISTS NOTIFY_STATUS STRING DEFAULT 'PENDING';

ALTER TABLE GOLD.GOLD_FLIGHT_DATA
ADD COLUMN IF NOT EXISTS NOTIFY_TS TIMESTAMP_LTZ;

ALTER TABLE GOLD.GOLD_FLIGHT_DATA
ADD COLUMN IF NOT EXISTS LAST_NOTIFIED_DELAY NUMBER(3,0);

ALTER TABLE GOLD.GOLD_FLIGHT_DATA
ADD COLUMN IF NOT EXISTS LAST_NOTIFIED_AT TIMESTAMP_NTZ;
