USE SCHEMA FLYWISE_AI_DB.GOLD;

CREATE OR REPLACE TABLE GOLD.FLIGHT_NOTIFICATIONS_OUTBOX (
    OUTBOX_ID           NUMBER AUTOINCREMENT,
    FLIGHT_ID           NUMBER,
    FLIGHT_IATA         VARCHAR,
    AIRLINE_NAME        VARCHAR,
    DEPARTURE_IATA      VARCHAR,
    ARRIVAL_IATA        VARCHAR,
    DEPARTURE_DATE      DATE,
    DEPARTURE_TIME      TIME,
    CURRENT_DELAY_MIN   NUMBER,
    MESSAGE_TEXT        STRING,
    USER_NAME           VARCHAR,
    USER_EMAIL          VARCHAR,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    STATUS              VARCHAR DEFAULT 'PENDING',   -- PENDING | SENT | FAILED
    SENT_AT             TIMESTAMP_NTZ
);
