USE SCHEMA FLYWISE_AI_DB.GOLD;

CREATE OR REPLACE TASK GOLD.NOTIFICATION_AGENT_TASK
    WAREHOUSE = FLYWISE_WH
    SCHEDULE = '5 MINUTE'
AS
    CALL GOLD.PREPARE_FLIGHT_NOTIFICATIONS();

ALTER TASK GOLD.NOTIFICATION_AGENT_TASK RESUME;
